version: '3.10'

services:
  db_1:
    container_name: db_1
    ports:
      - "5432:5432"
    image: postgres:14.3
    restart: always
    env_file:
      - .env
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_USER=${DB_USER}
  web:
    container_name: progress
    build: ./
    volumes:
      - ./source:/src
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db_1
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db_1:5432/postgres
    env_file: .env




